version: '3'

services:
  wasmdnode0:
    container_name: wasmdnode0
    image: "tendermint/wasmdnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-fetchd.log}
    volumes:
      - ./build:/fetchd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  wasmdnode1:
    container_name: wasmdnode1
    image: "tendermint/wasmdnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-fetchd.log}
    volumes:
      - ./build:/fetchd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  wasmdnode2:
    container_name: wasmdnode2
    image: "tendermint/wasmdnode"
    environment:
      - ID=2
      - LOG=${LOG:-fetchd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/fetchd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  wasmdnode3:
    container_name: wasmdnode3
    image: "tendermint/wasmdnode"
    environment:
      - ID=3
      - LOG=${LOG:-fetchd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/fetchd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

