version: '3'

services:
  fetchdnode0:
    container_name: fetchdnode0
    image: "tendermint/fetchdnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-fetchd.log}
    volumes:
      - ./build:/fetchd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  fetchdnode1:
    container_name: fetchdnode1
    image: "tendermint/fetchdnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-fetchd.log}
    volumes:
      - ./build:/fetchd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  fetchdnode2:
    container_name: fetchdnode2
    image: "tendermint/fetchdnode"
    environment:
      - ID=2
      - LOG=${LOG:-fetchd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/fetchd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  fetchdnode3:
    container_name: fetchdnode3
    image: "tendermint/fetchdnode"
    environment:
      - ID=3
      - LOG=${LOG:-fetchd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/fetchd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

