---

- name: Copy binary
  copy:
    src: "{{GAIACLI_BINARY}}"
    dest: /usr/bin/fetchcli
    mode: 0755
  notify: restart fetchcli

- name: Copy service
  template:
    src: fetchcli.service.j2
    dest: /etc/systemd/system/fetchcli.service
  notify: systemctl

