---

- name: Stop service
  service: name=fetchd state=stopped

- name: Delete files
  file: "path={{item}} state=absent"
  with_items:
  - /usr/bin/fetchd
  - /home/fetchd/.fetchd
  - /home/fetchd/.fetchcli

