name: Build and push images
on:
  push:
    tags:
      - '*'

env:
  REGISTRY: gcr.io/fetch-ai-images

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Login to Docker hub, build and push
        run: |
          SHORTVERSION=${SOURCE_TAG%.*}
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker build -t fetchai/fetchd:$SOURCE_TAG -f Dockerfile.hub .
          docker push fetchai/fetchd:$SOURCE_TAG
          docker tag fetchai/fetchd:$SOURCE_TAG fetchai/fetchd:$SHORTVERSION
          docker push fetchai/fetchd:$SHORTVERSION
        env:
          SOURCE_TAG: ${{ steps.tag_name.outputs.SOURCE_TAG }}

      - name: Setup GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_KEY_IMAGES }}
      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      - name: Build and push to GCR
        run: |
          SHORTVERSION=${SOURCE_TAG%.*}
          docker build -t $REGISTRY/fetchd:$SOURCE_TAG -f Dockerfile.gcr . --build-arg VERSION=$SOURCE_TAG
          docker push $REGISTRY/fetchd:$SOURCE_TAG
          docker tag $REGISTRY/fetchd:$SOURCE_TAG $REGISTRY/fetchd:$SHORTVERSION
          docker push $REGISTRY/fetchd:$SHORTVERSION
        env:
          SOURCE_TAG: ${{ steps.tag_name.outputs.SOURCE_TAG }}
