name: Build and push images
on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - release/*  
env:
  REGISTRY: gcr.io/fetch-ai-images

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Get tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Login to Docker hub, build and push
        run: |
          SOURCE_TAG="v0.1.1"
          SHORTVERSION=${SOURCE_TAG%.*}
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker build -t fetchai/wasmd:$SOURCE_TAG -f Dockerfile.hub .
          docker push fetchai/wasmd:$SOURCE_TAG
          docker tag fetchai/wasmd:$SOURCE_TAG fetchai/wasmd:$SHORTVERSION
          docker push fetchai/wasmd:$SHORTVERSION
        # env:
        #   SOURCE_TAG: ${{ steps.tag_name.outputs.SOURCE_TAG }}

      - name: Setup GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_KEY_IMAGES }}
      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      - name: Build and push
        run: |
          SOURCE_TAG="v0.1.1"
          SHORTVERSION=${SOURCE_TAG%.*}
          docker build -t $REGISTRY/cosmos-wasmd:$SOURCE_TAG -f Dockerfile.gcr .
          docker push $REGISTRY/cosmos-wasmd:$SOURCE_TAG
          docker tag $REGISTRY/cosmos-wasmd:$SOURCE_TAG $REGISTRY/cosmos-wasmd:$SHORTVERSION
          docker push $REGISTRY/cosmos-wasmd:$SHORTVERSION
      #   env:
      #     SOURCE_TAG: ${{ steps.tag_name.outputs.SOURCE_TAG }}