name: Build and push images
on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish Public Images
        uses: ejfitzgerald/action-docker-tag@v1
        with:
          dockerfile: hub.Dockerfile
          repo: fetchai/fetchd

      - name: Setup GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_KEY_IMAGES }}

      - name: Login to GCR Registry
        run: |
          gcloud auth configure-docker

      - name: Build and Publish Private Images
        uses: ejfitzgerald/action-docker-tag@v1
        with:
          dockerfile: gcr.Dockerfile
          repo: gcr.io/fetch-ai-images/fetchd
