name: Build and test
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker container
        run: |
          docker build \
            --no-cache \
            --progress plain \
            --tag fetch_cosmos_fetchd:$GITHUB_SHA \
            --file ./ci.Dockerfile \
            ./
      - name: Run make test
        run: |
          docker run --rm fetch_cosmos_fetchd:$GITHUB_SHA \
            make test
